version: "3.9"

services:

  zabbix-postgres:
    image: postgres:latest
    container_name: zabbix-postgres
    hostname: zabbix-postgres
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_ROOT_USER: root
      POSTGRES_ROOT_PASSWORD: 1234
      POSTGRES_DATABASE: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 1234
    networks:
      - default
    volumes:
      - /opt/zabbix/postgres/data:/var/lib/postgresql

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 1234
    networks:
      default:
        ipv4_address: 172.28.0.254
    depends_on:
      - zabbix-postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    container_name: zabbix-web
    hostname: zabbix-web
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: 1234
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Moscow"
    ports:
      - 10051:8080
      - 8443:8443
    networks:
      - default
    depends_on:
      - zabbix-postgres
      - zabbix-server

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
